project:
  type: website
  output-dir: docs
website:
  title: "Feburary Report"
  navbar:
    left:
      - href: weekly report.qmd
        text: Summary of PSM Analysis
      - href: Journal.qmd
        text: Journal Type
      - href: Prof reflec.qmd
        text: Prof Relfec
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
